services:
  postgres:
    image: postgres:17.6
    container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    env_file:
      - .env
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_DB_URL_HOST: ${KEYCLOAK_DB_HOST}
      KC_DB_URL_DATABASE: ${KEYCLOAK_DB_NAME}
      KC_DB_SCHEMA: public
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: ${KEYCLOAK_HTTP_PORT}
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_HTTP_PORT: 8080
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_HEALTH_ENABLED: true
      KC_LOG_LEVEL: INFO
    ports:
      - "${KEYCLOAK_HTTP_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy
    command: ["start-dev"]
    networks:
      - app-network
    volumes:
      - keycloak_data:/opt/keycloak/data
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;grep 'HTTP/1.1 200' <&3"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  backend:
    image: davideeh/bugboard26-swe-backend
    container_name: express_backend
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: 3000
      CLIENT_URL: ${CLIENT_URL}

      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_CONNECTION_URI: ${DB_CONNECTION_URI}
      DIALECT: ${DIALECT}

      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_BACKEND_CLIENT_ID: ${KEYCLOAK_BACKEND_CLIENT_ID}
      KEYCLOAK_BACKEND_CLIENT_SECRET: ${KEYCLOAK_BACKEND_CLIENT_SECRET}
      KEYCLOAK_AUTH_URL: ${KEYCLOAK_AUTH_URL}
      KEYCLOAK_TOKEN_URL: ${KEYCLOAK_TOKEN_URL}
      KEYCLOAK_USERINFO_URL: ${KEYCLOAK_USERINFO_URL}

      SESSION_SECRET: ${SESSION_SECRET}
    ports:
      - "${BACKEND_PORT}:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - app-network
    command: npm run dev

  frontend:
    image: davideeh/bugboard26-swe-frontend
    container_name: angular_frontend
    env_file:
      - .env
    environment:
      KEYCLOAK_URL: ${KEYCLOAK_PUBLIC_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_FRONTEND_CLIENT_ID}
      BACKEND_URL: http://localhost:${BACKEND_PORT}
    ports:
      - "${FRONTEND_PORT}:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
      - keycloak
    networks:
      - app-network
    command: npm start -- --host 0.0.0.0

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASS}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:
  pgadmin_data:
  keycloak_data:

networks:
  app-network:
    driver: bridge